name: 'process-dispatch'
description: 'Process OnFusionCoe dispatch operation'
inputs:
  dispatch_action:
    description: 'The action to be taken during the dispatch operation workflow'
    required: true

jobs:
  system-check:
    - name: confirm running
      run: |
        echo "repository variable : ${{ inputs.dispatch_action }}"
