name: 'process-dispatch'
description: 'Process OnFusionCoe dispatch operation'

on:
  workflow_call:
    inputs:

      dispatch_action:
        description: 'The action to be taken during the dispatch operation workflow'
        required: true
        type: string

      environment_url:
        description: 'URL of Power Platform environment to connect with; e.g. "https://test-env.crm.dynamics.com"'
        required: false

      app_id:
        description: 'The application id to authenticate with. Setting this input makes app-id, tenant-id and client-secret required; specifying alternate "username" credential set of inputs will result in an error.'
        required: false

      client_secret:
        description: 'The client secret to authenticate with. Required if authenticating with app-id.'
        required: false

      tenant_id:
        description: 'Tenant id if using app-id & client secret to authenticate.'
        required: false

      solution_name:
        description: 'Name of solution to export'
        required: false    

      cloud:
        description: 'Cloud instance to authenticate with. Default: Public. See "pac auth create help" for valid cloud instance names'
        required: false
        default: 'Public'
             

runs:
  using: "composite"
  steps:
    
    - name: Run Env
    run: |
      echo "running action ${{inputs.dispatch_action}}"

    - name: Ensure Power Platform
      uses: fusioncoe/onfusioncoe-actions/ensure-powerplatform-install@v0
      

#jobs:
#  process-dispatch-action:
#    runs-on: windows-latest

 #   steps:
 #   - name: Run Env
 #     run: env
    
    #- name: confirm running
    #  run: |
    #    echo "repository variable : ${{inputs.dispatch_action}}"