name: 'process-dispatch'
description: 'Process OnFusionCoe dispatch operation'

on:
  workflow_call:
    inputs:
      dispatch_action:
        description: 'The action to be taken during the dispatch operation workflow'
        required: true
        type: string
  #secrets:
  #  token:
  #  required: true


jobs:
  process-dispatch-action:
    runs-on: windows-latest

    steps:
    - name: Run Env
      run: env
    
    #- name: confirm running
    #  run: |
    #    echo "repository variable : ${{inputs.dispatch_action}}"