name: 'process-service-repo-dispatch'
description: 'Process OnFusionCoe service repo dispatch operation'

on:
  workflow_call:
    inputs:

      cicd-app-id:
        description: 'The application id to authenticate with.'
        required: false

      cicd-sp-client-secret:
        description: 'The client secret to authenticate with. Required if authenticating with app-id.'
        required: false

      cicd-tenant-id:
        description: 'Tenant id if using app-id & client secret to authenticate.'
        required: false

      cicd-cloud:
        description: 'Cloud instance to authenticate with. Default: Public. See "pac auth create help" for valid cloud instance names'
        required: false

runs:
  using: "composite"
  steps:
    
    - name: Generating Credentials
      shell: pwsh    
      run: |
        echo "Handling dispatch operation ${{github.event.action}}"
        # get-content ${{ github.event_path }} 

        $TenantId = "${{ inputs.cicd-tenant-id }}"
        $AppClientId="${{ inputs.cicd-app-id }}"        
        $ClientSecret ="${{ inputs.cicd-sp-client-secret }}"
          
        $RequestBody = @{client_id=$AppClientId;client_secret=$ClientSecret;grant_type="client_credentials";scope=" https://graph.microsoft.com/.default";}
        $OAuthResponse = Invoke-RestMethod -Method Post -Uri https://login.microsoftonline.com/$TenantId/oauth2/v2.0/token -Body $RequestBody
        $AccessToken = $OAuthResponse.access_token

        echo "SPN_BEARER=bearer $AccessToken" >> $GITHUB_ENV

    - name: Checking Credentials
      shell: pwsh    
      run: |
        echo "Checking for bearer token: ${{env.SPN_BEARER}}"              


