name: 'process-service-repo-dispatch'
description: 'Process OnFusionCoe service repo dispatch operation'

on:
  workflow_call:
    inputs:

      action:
        description: 'The type of operation'
        required: true
        type: string

runs:
  using: "composite"
  steps:
    
    - name: Run Env
      shell: pwsh    
      run: |
        echo "Handling dispatch operation ${{inputs.action}}"
        get-content ${{ github.event_path }} 

    - name: Testing Access To Event inputs
      shell: pwsh    
      run: |
        echo "Total count: ${{ github.event.client_payload.total_count }}"                     
